css_selectors:
  chapter_title: ".bottom-wrapper > div:nth-child(2) > div:nth-child(1)"
  chapter_content: "#novel_content"
prompt: new_prompt.md
preferences:
  max_translation_attempts: 7 # Maximum attempts to translate a chapter before failing
  translation_completeness_threshold: 0.75 # Number of lines that must appear in the translation (as a percentage of the original work) to be considered complete